# Generated by Django 5.1.1 on 2024-09-22 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
