# Generated by Django 5.1.1 on 2024-09-22 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_staffattendance_date_studentattendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Validation Failed', 'Validation Failed')], max_length=20)),
                ('code_validation', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
