# Generated by Django 5.1.1 on 2024-09-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_attendancerecord_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='location_validation',
            field=models.CharField(default='Passed', max_length=100),
            preserve_default=False,
        ),
    ]
