# Generated by Django 5.1.1 on 2024-09-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_studentattendance_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='batch',
            field=models.CharField(default='G1', max_length=100),
            preserve_default=False,
        ),
    ]
