# Generated by Django 5.1.1 on 2024-09-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_attendancerecord_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Doubt', 'Doubt')], default='Absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='code_validation',
            field=models.CharField(default='Failed', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='location_validation',
            field=models.CharField(default='Failed', max_length=100),
        ),
    ]
